// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yycywbwdlvjehqfgodod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5Y3l3YndkbHZqZWhxZmdvZG9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTU1MjIsImV4cCI6MjA2NDY5MTUyMn0.9Hj2oJMXxZ6xsbAF_Ds3448b-Vwm-ocodofvUnTVjD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);